services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        BACKEND_URL: http://construlink-backend:3001
        NEXT_PUBLIC_MAPBOX_TOKEN: ${NEXT_PUBLIC_MAPBOX_TOKEN}
    container_name: construlink-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://construlink-backend:3001
    depends_on:
      - backend
    networks:
      - carbelle_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: construlink-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - carbelle_net

networks:
  carbelle_net:
    external: true
    name: portal_espaco_carbelle_default
